apiVersion: apps/v1
kind: Deployment

metadata:
  name: devdeploy
  labels:
    appname: devdepoy
  annotations:
     kubernetes.io/change-cause: "deploy v2 version"
spec:
  replicas: 3
  selector:
    matchLabels:
      type: dev
  template:
    metadata:
      name: dev
      labels:
        type: dev
    spec:
      containers:
        - name: devcontainer
          image: coolgourav147/nginx-custom

